name: Acquire activation file
on:
  workflow_dispatch: {}
  push:
    branches:
      - ci-test
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: windows-2019
    steps:
      # Request manual activation file
      - uses: actions/checkout@v3
      - runs: |
          cd ci\unity-req-license
          powershell .\req-license.ps1
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: license-request
          path: ci\unity-req-license
