name: Run tests
on:
  workflow_dispatch: {}
  push:
    branches:
      - ci-test

jobs:
  test-activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet tool install --global vrchat.vpm.cli
      - run: vpm add package com.vrchat.avatars
      
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2019.4.31f1-base-0
          testMode: EditMode
